version: '3.9'

services:
  mailpit:
    image: ${IMAGE_NAME:-'axllent/mailpit:latest'}
    container_name: ${CONTAINER_NAME:-mailpit}
    restart: unless-stopped
    ports:
      - '${MAILPIT_SMTP_PORT:-1025}:1025'
      - '${MAILPIT_WEB_PORT:-8025}:8025' 
