# Version with a single Directus
version: '3'

volumes:
  uploads:

networks:
  proxy:
    external: true

services:

  directus:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - ${DIRECTUS_PORT:-8055}:8055
    volumes:
      - ${HOST_UPLOADS:-uploads}:${STORAGE_LOCAL_ROOT:-/directus/uploads}
    networks:
      - proxy
    environment:
      TZ: ${TZ}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      WEBSOCKETS_ENABLED: true
#      LOG_LEVEL: ${LOG_LEVEL}
      DB_CLIENT: '${DB_CLIENT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'

#      CACHE_ENABLED: ${CACHE_ENABLED}
#      CACHE_STORE: ${CACHE_STORE}
#      CACHE_REDIS: redis://cache:${REDIS_PORT}

#      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      #STORAGE_LOCAL_PUBLIC_URL: ${STORAGE_LOCAL_PUBLIC_URL}
#      STORAGE_LOCAL_DRIVER: ${STORAGE_LOCAL_DRIVER}
#      STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT}

#      EMAIL_FROM: no-reply@directus.io #Email address from which emails are sent. Default: `no-reply@directus.io`
#      EMAIL_TRANSPORT: smtp  #What to use to send emails. One of `sendmail`, `smtp`. Based on the transport used, you must also provide the following configurations.
#      Sendmail (sendmail):
#      EMAIL_SENDMAIL_NEW_LINE: unix # — What new line style to use in sendmail. Default: unix
#      EMAIL_SENDMAIL_PATH: /usr/sbin/sendmail # — Path to your sendmail executable. Default: /usr/sbin/sendmail
#      SMTP (smtp)
#      EMAIL_SMTP_HOST: #— SMTP Host
#      EMAIL_SMTP_PORT: #— SMTP Port
#      EMAIL_SMTP_USER: #— SMTP User
#      EMAIL_SMTP_PASSWORD: #— SMTP Password
#      EMAIL_SMTP_POOL: #— Use SMTP pooling
#      EMAIL_SMTP_SECURE: #— Enable TLS
