# Independent nginx version with custom certs
version: '3.9'
services:
  static-site:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html
      - /home/ubuntu/docker/ssl-cert:/etc/nginx/certs
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=${TZ}
