version: "3"
networks:
  proxy:
    external: true
services:
  dozzle:
    container_name: dozzle
    networks:
      proxy:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8090:8080
    restart: unless-stopped