---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

local-docker:
  socket: /var/run/docker.sock

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-remote-docker:
#   host: 192.168.0.101
#   port: 275
#   tls:
#     keyFile: tls/key.pem
#     caFile: tls/ca.pem
#     certFile: tls/cert.pem